spring :
  datasource:
    url : jdbc:postgresql://localhost:5432/kafka
    username: postgres
    password: imad
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: wikimedia-group
    auto-offset-reset: earliest

server:
  port: 8081
